Repository axnsan12/drf-yasg, pull requests merged in 2022-07, with the labels that each got.

#757 Allow specifying response as a reference
  src/drf_yasg/inspectors/view.py
Labels: enhancement, 1.21.x

#695 Added `many` support to example code.
  docs/custom_spec.rst
Labels: documentation, 1.21.x

#445 Drf extra fields base64 integration
  README.rst
Labels: documentation, 1.21.x

#678 docs: update readme.rst
  README.rst
  testproj/todo/views.py
  tests/urlconfs/non_public_urls.py
Labels: documentation, 1.21.x

#797 Add prepublish compatibility checks, a composite installation action and explicitly set tox targets
  .github/actions/install/action.yml
  .github/workflows/publish.yml
  .github/workflows/review.yml
  README.rst
  docs/changelog.rst
  requirements/publish.txt
Labels: enhancement, 1.21.x

#742 handle errors rendering with TemplateHTMLRenderer
  src/drf_yasg/renderers.py
Labels: bug, 1.21.x

#717 add support for working with pytz object field
  src/drf_yasg/utils.py
Labels: bug, enhancement, 1.21.x

#688 Add checker for allow_null attr
  src/drf_yasg/inspectors/base.py
Labels: bug, enhancement, 1.21.x
